# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'NewFeeds' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewFeeds
  pod 'Kingfisher', '5.5.0'
  pod 'Codextended'
  pod 'Alamofire', '4.8.2'
  pod 'KRProgressHUD'

  target 'NewFeedsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewFeedsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
